src/matchmaker/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    # Examples:
    url(r'^$', 'newsletter.views.home', name='home'),
    url(r'^question/(?P<id>\d+)$', 'questions.views.single', name='question_single'),
    url(r'^question/$', 'questions.views.home', name='question_home'),
    url(r'^contact/$', 'newsletter.views.contact', name='contact'),
    url(r'^about/$', 'matchmaker.views.about', name='about'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/newsletter/models.py
from django.db import models

# Create your models here.
class SignUp(models.Model):
	email = models.EmailField()
	full_name = models.CharField(max_length=120, blank=True, null=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __unicode__(self): #Python 3.3 is __str__
		return self.email

src/questions/models.py
from __future__ import unicode_literals

from django.db import models


class Question(models.Model):
    text = models.TextField()
    active = models.BooleanField(default=True)
    draft = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    # answers = models.ManyToManyField('Answer')

    def __unicode__(self):
        return self.text[:10]


class Answer(models.Model):
    question = models.ForeignKey(Question)
    text = models.CharField(max_length=120)
    active = models.BooleanField(default=True)
    draft = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __unicode__(self):
        return self.text[:10]

src/newsletter/forms.py
from django import forms

from .models import SignUp

class ContactForm(forms.Form):
	full_name = forms.CharField(required=False)
	email = forms.EmailField()
	message = forms.CharField()


class SignUpForm(forms.ModelForm):
	class Meta:
		model = SignUp
		fields = ['full_name', 'email']
		### exclude = ['full_name']
	
	def clean_email(self):
		email = self.cleaned_data.get('email')
		email_base, provider = email.split("@")
		domain, extension = provider.split('.')
		# if not domain == 'USC':
		# 	raise forms.ValidationError("Please make sure you use your USC email.")
		if not extension == "edu":
			raise forms.ValidationError("Please use a valid .EDU email address")
		return email

	def clean_full_name(self):
		full_name = self.cleaned_data.get('full_name')
		#write validation code.
		return full_name

src/questions/forms.py
from django import forms


class UserResponseForm(forms.Form):
    question_id = forms.IntegerField()
    answer_id = forms.IntegerField()

src/matchmaker/views.py
from django.shortcuts import render


def about(request):
	return render(request, "about.html", {})

src/newsletter/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render

from .forms import ContactForm, SignUpForm
from .models import SignUp
from questions.models import Question



# Create your views here.
def home(request):
    title = 'Sign Up Now'
    form = SignUpForm(request.POST or None)
    context = {
        "title": title,
        "form": form
    }
    if form.is_valid():
        instance = form.save(commit=False)

        full_name = form.cleaned_data.get("full_name")
        if not full_name:
            full_name = "New full name"
        instance.full_name = full_name

        instance.save()
        context = {
            "title": "Thank you"
        }

    if request.user.is_authenticated():
        queryset = Question.objects.all().order_by('-timestamp')
        context = {
            "queryset": queryset
        }
        return render(request, "questions/home.html", context)

    return render(request, "home.html", context)


def contact(request):
    title = 'Contact Us'
    title_align_center = True
    form = ContactForm(request.POST or None)
    if form.is_valid():
        # for key, value in form.cleaned_data.iteritems():
        # 	print key, value
        # 	#print form.cleaned_data.get(key)
        form_email = form.cleaned_data.get("email")
        form_message = form.cleaned_data.get("message")
        form_full_name = form.cleaned_data.get("full_name")
        # print email, message, full_name
        subject = 'Site contact form'
        from_email = settings.EMAIL_HOST_USER
        to_email = [from_email, 'youotheremail@email.com']
        contact_message = "%s: %s via %s" % (
            form_full_name,
            form_message,
            form_email)
        some_html_message = """
		<h1>hello</h1>
		"""
        send_mail(subject,
                  contact_message,
                  from_email,
                  to_email,
                  html_message=some_html_message,
                  fail_silently=True)

    context = {
        "form": form,
        "title": title,
        "title_align_center": title_align_center,
    }
    return render(request, "forms.html", context)

src/questions/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Question, Answer

from .forms import UserResponseForm


def single(request, id):
    try:
        instance = Question.objects.get(id=id)
    except:
        raise Http404
    if request.user.is_authenticated():
        form = UserResponseForm(request.POST or None)
        if form.is_valid():
            print form.cleaned_data
            question_id = form.cleaned_data.get('question_id')
            answer_id = form.cleaned_data.get('answer_id')
            question_instance = Question.objects.get(id=question_id)
            answer_instance = Answer.objects.get(id=answer_id)
            print question_instance.text, answer_instance.text

        queryset = Question.objects.all().order_by('-timestamp')
        instance = queryset[id]
        context = {
            "form": form,
            "instance": instance,
            # "queryset": queryset
        }
        return render(request, "questions/home.html", context)
    else:
        raise Http404


def home(request):
    if request.user.is_authenticated():
        form = UserResponseForm(request.POST or None)
        if form.is_valid():
            print form.cleaned_data
            question_id = form.cleaned_data.get('question_id')
            answer_id = form.cleaned_data.get('answer_id')
            question_instance = Question.objects.get(id=question_id)
            answer_instance = Answer.objects.get(id=answer_id)
            print question_instance.text, answer_instance.text

        queryset = Question.objects.all().order_by('-timestamp')
        instance = queryset[0]
        context = {
            "form": form,
            "instance": instance,
            # "queryset": queryset
        }
        return render(request, "questions/home.html", context)
    else:
        raise Http404

src/templates/about.html
{% extends "base.html" %}



{% block content %}

<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>About Us</h1>
<p>This is about us. This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.</p>
<p>This is about us. This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.</p>
<p>This is about us. This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.</p>
</div>

</div>


{% endblock %}

src/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}MVP Landing{% endblock %}</title>

    {% include 'head_css.html' %}

      <style>
      {% block style %}{% endblock %}
      </style>



  </head>

  <body>
  {% include 'navbar.html' %}

{% block jumbotron %}
          
            {% endblock %}
    <div class="container">
            

          
            {% block content %}

            {% endblock %}
              

    </div> <!-- /container -->

    {% include "javascript.html" %}
    
    
  </body>
</html>

src/templates/example_fluid.html
{% extends "base.html" %}

{% block jumbotron %}
_
{% endblock %}

{% block content %}

<div class="row">
<div class="col-sm-3" style='background-color:orange;'>




             .col-md-4



             </div>

</div>

<div class="row">
  <div class="col-md-8 col-sm-6" style='background-color:red;'>.col-md-8
        <div class="row">
             <div class="col-md-6 col-sm-8 col-xs-2" style='background-color:orange;'>




             .col-md-4



             </div>
            <div class="col-md-6 col-sm-4 col-xs-10" style='background-color:yellow;'>.col-md-4</div>

        </div>

  </div>
  <div class="col-md-4 col-sm-6" style='background-color:blue;'>.col-md-4

    <div class="row">
             <div class="col-md-12" style='background-color:purple;'>.col-md-4</div>

        </div>

    </div>
</div>
<!-- <div class="row">
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
</div>
<div class="row">
  <div class="col-md-6">.col-md-6</div>
  <div class="col-md-6">.col-md-6</div>
</div> -->

{% endblock %}

src/templates/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}





<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>


{% if title %}
<h1 class='{% if title_align_center %}text-align-center{% endif %}'>{{ title }}</h1>
{% endif %}

<form method='POST' action=''>{% csrf_token %}
{{ form|crispy }}

<input class='btn btn-default' type='submit' value='Submit' />

</form>
</div>
</div>
{% endblock %}

src/templates/head_css.html
{% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
     <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

src/templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block head_title %}Welcome | {{ block.super }}{% endblock %}

<style>
{% block style %}
.navbar-static-top {
	margin-bottom: 0px !important;
}

.jumbotron {
	background-color:#0E3D14;
	color: #FFF;
}

{% endblock %}
</style>


     
{% block jumbotron %}
 {% if not request.user.is_authenticated %}

<div class="jumbotron">
 <div class="container">
	<div class="row">
		<div class='col-sm-6'>
		<h1>Matchmaker</h1>
		<p>The MVP Landing project is designed to get your project started. The goal is to help you launch as soon as possible with the least amount of investment using time or money. Join Us today.</p>
		<p>
		<a class="btn btn-lg btn-primary" href="" role="button">Join Us &raquo;</a>
		</p>
		</div>
		<div class='col-sm-6' >
			<iframe width="560" height="315" src="https://www.youtube.com/embed/2uLYO1LUf6Q" frameborder="0" allowfullscreen></iframe>

 		</div>
		</div>
	</div>
 </div>
 {% endif %}
{% endblock %}




{% block content %}
 {% if request.user.is_authenticated %}
<h1>You are logged in!</h1>

	{% if queryset %}
	<h2>Welcome Staff</h2>
	<table class='table'>
	{% for instance in queryset %}
		<tr><td>{{ forloop.counter }}</td><td>{{ instance.email }}</td><td>{{ instance.full_name }}</td><td>{{ instance.timestamp|timesince }} ago</td></tr>
		{% if instance.email == "abc@gmail.edu" %}
		<tr><td>is equal</td></tr>
		{% endif %}
	{% endfor %}
	</table>

	{% endif %}

 {% else %}
<div class="row">

  <div class="col-sm-3 pull-right">
  	
			<p class='lead text-align-center'>{{ title }}</p>

			<form method='POST' action=''>{% csrf_token %}
			{{ form|crispy }}

			<input class='btn btn-primary' type='submit' value='Sign Up' />

			</form>
	</div>

	<div class='col-sm-3'>
<p class='lead text-align-center'>Django &amp; Bootstrap</p>
			<img src='{% static "img/marketing1.jpg" %}' class='img-responsive' />
</div>

<div class='col-sm-3'>
<p class='lead text-align-center'>Created for Starters 
<br/>
<span class='fa-stack fa-lg fa-5x'>
<i class='fa fa-comment-o fa-stack-2x'></i>
<i style='color:yellow;' class="fa fa-bolt fa-stack-1x"></i>

</span>
</p>

</div>

<div class='col-sm-3'>
<p class='lead text-align-center'>Always Open Source <br/><br/>

<span class="fa-stack fa-lg fa-5x">
<i class="fa fa-circle-o-notch fa-stack-2x"></i>
  <!-- <i class="fa fa-square-o fa-stack-2x"></i> -->
  <i class="fa fa-github fa-stack-1x"></i>
</span>
</p>


</div>


</div>
{% endif %}

{% endblock %}

src/templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

src/templates/navbar.html
   {% load staticfiles %}

   <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/mvp_landing_logo.png' %}" /></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>


          <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
            <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'registration_register' %}">Register</a></li>
            {% endif %}
          </ul>

          {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
            <form class='navbar-form navbar-right' method='POST' action='{% url "auth_login" %}'>{% csrf_token %}
              <div class='form-group'>
                  <input type='text' class='form-control' name='username' placeholder='Username' /> 
              </div>
              <div class='form-group'>
                  <input type='password' class='form-control' name='password' placeholder='Password' />
              </div>
              <button type='submit' class='btn btn-default'>Login</button>
          </form>
          {% endif %}


        </div><!--/.nav-collapse -->
      </div>
    </nav>

src/templates/questions/home.html
{% extends 'base.html' %}


{% block content %}


    <form method="post" action=""> {% csrf_token %}
        <h4>{{ instance.text }}</h4>
        <input type="hidden" name="question_id" value="{{ instance.id }}">
        {% for answer in instance.answer_set.all %}
            <input type="radio" name="answer_id" value="{{ answer.id }}"> {{ answer.text }} </br>
        {% endfor %}
        <input type="submit" value="Save and continue">
    </form>





{% endblock content %}